(function (root, factory) {
  const value = factory();

  if (typeof module === "object" && module.exports) {
    module.exports = value;
  }

  if (root) {
    root.ComintLegacyUrlMap = value;
  }
})(typeof window !== "undefined" ? window : globalThis, function () {
  return {
  "izgotovlenie-i-pechat-beydzhey": "/cifrovaya-pechat/bejdzh/",
  "bloki-dlya-zapisey-kub-bloki": "/cifrovaya-pechat/bloki-dlya-zapisej-kub-bloki/",
  "izgotovlenie-i-pechat-bloknotov-s-logotipom": "/cifrovaya-pechat/bloknoty/",
  "pechat-broshyur": "/cifrovaya-pechat/broshury/",
  "reklamnye-buklety-pechat-izgotovlenie-i-dizayn": "/cifrovaya-pechat/buklety/",
  "pechat-tsennikov": "/cifrovaya-pechat/cenniki/",
  "dizayn-poligrafii": "/cifrovaya-pechat/design-poligrafii/",
  "diskontnye-karty": "/cifrovaya-pechat/discount/",
  "firmennye-konverty-s-logotipom": "/cifrovaya-pechat/firmennye-konverty-s-logotipom/",
  "pechat-flaerov": "/cifrovaya-pechat/flaery/",
  "garantiynye-talony": "/cifrovaya-pechat/garantijnye-talony/",
  "pechat-instruktsiy": "/cifrovaya-pechat/instrukciya/",
  "izgotovlenie-birok-i-yarlykov": "/cifrovaya-pechat/izgotovlenie-birok-i-yarlykov/",
  "izgotovlenie-i-pechat-otkrytok": "/cifrovaya-pechat/izgotovlenie-i-pechat-otkrytok/",
  "izgotovlenie-i-pechat-vizitok": "/cifrovaya-pechat/izgotovlenie-i-pechat-vizitok/",
  "kartochki-s-nomerom-telefona-dlya-mashin": "/cifrovaya-pechat/kartochki-s-telefonom-dlya-mashin/",
  "pechat-katalogov": "/cifrovaya-pechat/katalogi/",
  "magnity-i-bloki-dlya-zapisi": "/cifrovaya-pechat/magnityi-blok/",
  "pechat-i-izgotovlenie-firmennyh-papok": "/cifrovaya-pechat/papki/",
  "pechat-firmennyh-blankov": "/cifrovaya-pechat/pechat-firmennyh-blankov/",
  "pechat-reklamnyh-listovok": "/cifrovaya-pechat/pechat-listovok/",
  "pechat-menyu": "/cifrovaya-pechat/pechat-menyu/",
  "pechat-reklamnyh-plakatov-i-afish": "/cifrovaya-pechat/plakaty-afishy/",
  "razrabotka-i-pechat-prays-listov": "/cifrovaya-pechat/price_list/",
  "pechat-priglasitelnyh-i-vhodnyh-biletov": "/cifrovaya-pechat/priglasheniya-bilety/",
  "pechat-i-izgotovlenie-propuskov": "/cifrovaya-pechat/propusk/",
  "razdatochnye-materialy": "/cifrovaya-pechat/razdatochnue_materialu/",
  "pechat-sertifikatov-diplomov-blagodarnostey": "/cifrovaya-pechat/sertifikaty-diplomy/",
  "rassadki-i-priglasitelnye-na-svadbu": "/cifrovaya-pechat/svadebnaya-poligraphiya/",
  "pechat-fotografiy-bolshogo-formata": "/decor-interjera/fotografii/",
  "izgotovlenie-fotooboev-na-zakaz": "/decor-interjera/fotooboi/",
  "matirovanie-stekla-plenkoy-s-effektom-iney": "/decor-interjera/matirovanie-stekol/",
  "dekorativnye-nakleyki-na-steny-i-mebel-stikery-na-holodilnik": "/decor-interjera/naklejki-na-stenyi-i-mebel/",
  "pechat-na-holste-reproduktsiy-kartin-i-fotografiy": "/decor-interjera/pechat-na-xolste/",
  "pechat-posterov-i-plakatov-bolshogo-formata": "/decor-interjera/posteryi-i-plakatyi/",
  "skinali-dlya-kuhni": "/decor-interjera/skinali/",
  "trafarety-dlya-dekora": "/decor-interjera/trafaretyi-dlya-okraski-sten/",
  "akrilovye-paneli": "/info-pos/akrilovye-paneli/",
  "tsennikoderzhateli-iz-plastika-i-orgstekla": "/info-pos/czennikoderzhateli-iz-plastika-i-orgstekla/",
  "garderobnye-nomerki-birki-i-nomerki-dlya-klyuchey": "/info-pos/garderobnye-nomerki-birki-i-nomerki-dlya-klyuchej/",
  "hengery-izgotovlenie-i-pechat": "/info-pos/hengery-izgotovlenie-i-pechat-hengerov/",
  "izgotovlenie-reklamnyh-mobaylov": "/info-pos/izgotovlenie-reklamnyh-mobajlov/",
  "izgotovlenie-torgovoy-atributiki": "/info-pos/izgotovlenie-torgovoj-atributiki/",
  "kompleksnoe-oformlenie-magazina-reklamnoe-oformlenie-torgovogo-zala": "/info-pos/kompleksnoe-oformlenie-mest-prodazh/",
  "mulyazhi-produktov": "/info-pos/mulyazhi-produktov/",
  "pechat-shelftokerov": "/info-pos/pechat-shelftokerov/",
  "podstavki-pod-poligraficheskuyu-produktsiyu-iz-orgstekla": "/info-pos/podstavki-pod-poligraficheskuyu-produkcziyu-iz-orgstekla/",
  "podstavki-pod-tovary-iz-orgstekla": "/info-pos/podstavki-tovary/",
  "pos-materialy": "/info-pos/pos-materialy/",
  "reklamnye-stoppery": "/info-pos/reklamnye-stoppery/",
  "reklamnye-voblery": "/info-pos/reklamnye-voblery/",
  "informatsionnye-i-reklamnye-ukazateli-navigatsiya-v-torgovom-zale": "/info-pos/reklamnyie-ukazateli/",
  "rostovye-figury-hardpostery-tantamareski": "/info-pos/rostovye-figury-hardpostery-tantamareski/",
  "informatsionnye-stendy": "/info-stendyi-tablichki/informaczionnye-stendy/",
  "vyveski-i-tablichki-dlya-kabinetov-ofisnye-tablichki": "/info-stendyi-tablichki/ofisnyie-tablichki/",
  "bukletnitsy-napolnye-i-stoyki-dlya-bukletov": "/mobilnoe-reklamnoe-oborudovanie/bukletnicy/",
  "fold-up-stendy-shirmy": "/mobilnoe-reklamnoe-oborudovanie/fold-up/",
  "mobilnye-bannery": "/mobilnoe-reklamnoe-oborudovanie/mobilnye-stendy/",
  "pop-up-stendy": "/mobilnoe-reklamnoe-oborudovanie/pop-up-stendy/",
  "izgotovlenie-promo-stoek-i-promo-stolov": "/mobilnoe-reklamnoe-oborudovanie/promo-stojki/",
  "roll-up-stendy": "/mobilnoe-reklamnoe-oborudovanie/roll-ap-stendy/",
  "izgotovlenie-fasadnyh-tablichek-i-informatsionnyh-ukazateley": "/naruzhnaya-reklama/fasadnye-tablichki/",
  "izgotovlenie-svetovyh-obemnyh-bukv": "/naruzhnaya-reklama/obemnye-bukvy/",
  "oformlenie-pasporta-naruzhnoy-reklamy": "/naruzhnaya-reklama/oformlenie-naruzhnoj-reklamy/",
  "oformlenie-vitrin-magazinov-reklama-na-vitrinah": "/naruzhnaya-reklama/oformlenie-vitrin-minsk/",
  "izgotovlenie-reklamnyh-pilonov": "/naruzhnaya-reklama/pilony/",
  "reklamnye-shtendery": "/naruzhnaya-reklama/shtender/",
  "svetovye-koroba-laytboksy": "/naruzhnaya-reklama/svetovye-koroba/",
  "izgotovlenie-naruzhnyh-reklamnyh-vyvesok": "/naruzhnaya-reklama/vyveski/",
  "pechat-na-tkani": "/odezhda-i-tekstil/pechat-na-tkani-i-sumkah/",
  "dizayn-i-proektirovanie-vystavochnyh-stendov": "/oformlenie-vystavok/dizajn-expo-stendov/",
  "spetspredlozhenie-vystavka-pod-klyuch": "/oformlenie-vystavok/expo-komplex/",
  "mobilnye-vystavochnye-konstruktsii-dlya-stendov": "/oformlenie-vystavok/mobilnye-expo-konstrukcii/",
  "oformlenie-i-okleyka-vystavochnyh-stendov-grafikoy": "/oformlenie-vystavok/oformlenie-expo-stendov/",
  "karmannye-kalendari": "/pechat-i-izgotovlenie-kalendarej/karmannye-kalendari/",
  "kvartalnye-kalendari": "/pechat-i-izgotovlenie-kalendarej/kvartalnye-kalendari/",
  "nastolnye-kalendari-domiki": "/pechat-i-izgotovlenie-kalendarej/nastolnye-kalendari-domiki/",
  "perekidnye-nastennye-kalendari": "/pechat-i-izgotovlenie-kalendarej/perekidnye-nastennye-kalendari/",
  "nakleyki-na-avto": "/reklama-na-transporte/naklejki-na-avto/",
  "samokleyaschiesya-etiketki": "/samokleyushhayasya-produkcziya/etiketki/",
  "garantiynye-plomby-pechatnye": "/samokleyushhayasya-produkcziya/garantijnye-plomby-pechatnye/",
  "izgotovlenie-znakov-bezopasnosti": "/samokleyushhayasya-produkcziya/izgotovlenie-znakov-bezopasnosti/",
  "pechat-nakleek-iz-samokleyascheysya-bumagi": "/samokleyushhayasya-produkcziya/naklejka-iz-bymagi/",
  "plotternye-nakleyki": "/samokleyushhayasya-produkcziya/naklejki_plotter/",
  "napolnye-nakleyki": "/samokleyushhayasya-produkcziya/naklejki-na-pol/",
  "izgotovlenie-i-pechat-nakleek-na-samokleyuscheysya-plenke": "/samokleyushhayasya-produkcziya/naklejki-print/",
  "uslugi-plotternoy-rezki": "/samokleyushhayasya-produkcziya/plotternaya-rezka/",
  "samokleyaschiesya-trafarety": "/samokleyushhayasya-produkcziya/trafarety/",
  "pechat-bannerov": "/shirokoformatnaya-pechat/bannery/",
  "pechat-flagov-vympelov-znamen": "/shirokoformatnaya-pechat/flagi/",
  "press-voll-brendvoll-press-stena-fony-dekoratsii": "/shirokoformatnaya-pechat/fonyi-pressvolyi/",
  "reklamnye-bannery-rastyazhki": "/shirokoformatnaya-pechat/reklamnye-bannery-rastyazhki/",
  "stroitelnaya-setka-dlya-ograzhdeniya": "/shirokoformatnaya-pechat/setka/",
  "breloki-s-logotipom": "/suveniryi/breloki-s-logotipom/",
  "firmennye-bumazhnye-pakety-s-logotipom": "/suveniryi/bumazhnyie-paketyi/",
  "suvenirnye-nastennye-chasy-s-logotipom-kompanii": "/suveniryi/chasy/",
  "pechat-na-tkanevyh-sumkah": "/suveniryi/eko-sumki/",
  "ezhednevniki-i-planingi-s-logotipom": "/suveniryi/ezhednevniki/",
  "pechat-na-kruzhkah": "/suveniryi/firmennyie-kruzhki/",
  "tkanevye-bannernye-i-bumazhnye-flazhki": "/suveniryi/flazhki/",
  "fleshki-s-logotipom": "/suveniryi/fleshki-s-logotipom/",
  "kartonnye-korobki-i-pakety-dlya-upakovki": "/suveniryi/kartonnye-korobki-i-pakety-dlya-upakovki/",
  "kepki-s-logotipom": "/suveniryi/kepki/",
  "kovriki-dlya-myshi-s-pechatyu-logotipa": "/suveniryi/kovriki-dlya-myishi/",
  "pechat-logotipov-na-pazlah": "/suveniryi/pazlyi/",
  "pechat-na-magnitah": "/suveniryi/pechat-na-magnitax1/",
  "podarochnye-nabory": "/suveniryi/podarochnyie-naboryi/",
  "podstavki-pod-kruzhku": "/suveniryi/podstavki-iz-probki/",
  "polietilenovye-pakety-s-logotipom": "/suveniryi/polietilenovyie-paketyi/",
  "ruchki-s-logotipom": "/suveniryi/ruchki-s-logotipom/",
  "suveniry-dlya-medrabotnikov": "/suveniryi/suveniry-dlya-medrabotnikov/",
  "pechat-na-tarelkah": "/suveniryi/tarelki/",
  "uf-pechat": "/suveniryi/uf-pechat-v-minske/",
  "zazhigalki-s-logotipom": "/suveniryi/zazhigalki/",
  "zerkala-karmannye": "/suveniryi/zerkala-karmannye/"
};
});
